// <auto-generated />
namespace Module.Data.Migrations
{
    using System.CodeDom.Compiler;
    using System.Data.Entity.Migrations;
    using System.Data.Entity.Migrations.Infrastructure;
    using System.Resources;
    
    [GeneratedCode("EntityFramework.Migrations", "6.4.4")]
    public sealed partial class updateemployedescription : IMigrationMetadata
    {
        private readonly ResourceManager Resources = new ResourceManager(typeof(updateemployedescription));
        
        string IMigrationMetadata.Id
        {
            get { return "202407140323347_update-employe-description"; }
        }
        
        string IMigrationMetadata.Source
        {
            get { return null; }
        }
        
        string IMigrationMetadata.Target
        {
            get { return Resources.GetString("Target"); }
        }
    }
}
