// <auto-generated />
namespace Module.Data.Migrations
{
    using System.CodeDom.Compiler;
    using System.Data.Entity.Migrations;
    using System.Data.Entity.Migrations.Infrastructure;
    using System.Resources;
    
    [GeneratedCode("EntityFramework.Migrations", "6.4.4")]
    public sealed partial class createemployee : IMigrationMetadata
    {
        private readonly ResourceManager Resources = new ResourceManager(typeof(createemployee));
        
        string IMigrationMetadata.Id
        {
            get { return "202407091710424_create-employee"; }
        }
        
        string IMigrationMetadata.Source
        {
            get { return null; }
        }
        
        string IMigrationMetadata.Target
        {
            get { return Resources.GetString("Target"); }
        }
    }
}
