// <auto-generated />
namespace Module.Data.Migrations
{
    using System.CodeDom.Compiler;
    using System.Data.Entity.Migrations;
    using System.Data.Entity.Migrations.Infrastructure;
    using System.Resources;
    
    [GeneratedCode("EntityFramework.Migrations", "6.4.4")]
    public sealed partial class updatestudyprogram : IMigrationMetadata
    {
        private readonly ResourceManager Resources = new ResourceManager(typeof(updatestudyprogram));
        
        string IMigrationMetadata.Id
        {
            get { return "202407130208068_update-study-program"; }
        }
        
        string IMigrationMetadata.Source
        {
            get { return null; }
        }
        
        string IMigrationMetadata.Target
        {
            get { return Resources.GetString("Target"); }
        }
    }
}
