// <auto-generated />
namespace Module.Data.Migrations
{
    using System.CodeDom.Compiler;
    using System.Data.Entity.Migrations;
    using System.Data.Entity.Migrations.Infrastructure;
    using System.Resources;
    
    [GeneratedCode("EntityFramework.Migrations", "6.4.4")]
    public sealed partial class updateemployeename : IMigrationMetadata
    {
        private readonly ResourceManager Resources = new ResourceManager(typeof(updateemployeename));
        
        string IMigrationMetadata.Id
        {
            get { return "202407130056396_update-employeename"; }
        }
        
        string IMigrationMetadata.Source
        {
            get { return null; }
        }
        
        string IMigrationMetadata.Target
        {
            get { return Resources.GetString("Target"); }
        }
    }
}
